version: "3"

services:
  website-builder:
    build:
      context: ./web
    environment:
      - APP_ENV=${APP_ENV}
      - TTS_DOMAIN=${TTS_DOMAIN}
      - MP3_DOMAIN=${MP3_DOMAIN}
      - MEILISEARCH_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
      - MEILISEARCH_DOMAIN=${MEILISEARCH_DOMAIN}
    volumes:
      - website_source:/usr/paysdufle.fr/src
      - website_build:/usr/paysdufle.fr/build
    depends_on:
      - meilisearch
    networks:
      - pfle

  tts:
    build:
      context: ./tts
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
    volumes:
      - './tts/src/mp3:/usr/src/app/mp3'
    networks:
      - pfle

  website:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - './web/Caddyfile.${APP_ENV}:/etc/caddy/Caddyfile'
      - 'caddy_data:/data'
      - 'caddy_config:/config'
      - 'website_build:/srv/website'
      - './tts/src/mp3:/srv/mp3'
    depends_on:
      - website-builder
      - search
    networks:
      - pfle

  search:
    build:
      context: ./search
    environment:
      - MEILISEARCH_ENV=${MEILISEARCH_ENV}
      - MEILISEARCH_MASTER_KEY=${MEILISEARCH_MASTER_KEY}
    networks:
      - pfle

  meilisearch:
    image: 'getmeili/meilisearch:latest'
    command: ./meilisearch --master-key=${MEILISEARCH_MASTER_KEY} --no-analytics=true
    ports:
        - '7700'
    volumes:
        - 'meilisearch:/data.ms'
    networks:
      - pfle

networks:
  pfle:
      driver: bridge

volumes:
  website_source:
    driver: local
  website_build:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  meilisearch:
    driver: local