version: "3.3"

services:

  website-builder:
    build:
      context: ./web
    container_name: "website-builder"
    environment:
      - APP_ENV=${APP_ENV}
      - TTS_DOMAIN=${TTS_DOMAIN}
      - MP3_DOMAIN=${MP3_DOMAIN}
    volumes:
      - website_source:/usr/paysdufle.fr/src
      - website_build:/usr/paysdufle.fr/build
  
  tts:
    build:
      context: ./tts
    container_name: "tts"
    restart: unless-stopped
    environment:
      - APP_ENV=${APP_ENV}
    ports:
      - "8080"
    volumes:
      - ./tts/src/mp3:/usr/src/app/mp3

  website:
    image: 'caddy:latest'
    container_name: "website"
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web/Caddyfile.${APP_ENV}:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - website_build:/srv/website
      - ./tts/src/mp3:/srv/mp3
    depends_on:
      - "website-builder"

  prometheus:
    image: "prom/prometheus:latest"
    hostname: "prometheus"
    restart: always
    networks:
      - website_monitoring
    ports:
      - "9090:9090"
    user: nobody
    volumes:
      - "./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
      - "./config/prometheus/targets.yml:/etc/prometheus/targets.yml:ro"
      - "./config/prometheus/rules:/etc/prometheus/rules"
      - "prometheus_data:/prometheus"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.time=30d"
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-admin-api'

  blackbox-exporter:
    image: "prom/blackbox-exporter:latest"
    hostname: "blackbox"
    restart: always
    networks:
      - website_monitoring
    ports:
      - "9115:9115"
    volumes:
      - "./config/blackbox-exporter/blackbox-exporter.yml:/etc/prometheus/blackbox-exporter.yml"
    command:
      - "--config.file=/etc/prometheus/blackbox-exporter.yml"

volumes:
  website_source:
  website_build:
  caddy_data:
  caddy_config:
  prometheus_data:

networks:
  website_monitoring: